### ISSUE TITLE
Invalid address?

### ISSUE THREAD

**Issue by mrbluecoat** [ElrondNetwork/ledger-elrond#12]
I installed the app on Ledger Nano S per your instructions and ran the `ElrondTestApp_linux_v1.0.3` on Linux as instructed.  When I do so I get something like:

```
Nano S app version:  1.0.3
Network: Mainnet ; Contract data: Disabled
Chain ID: 1
Tx version: 1
Retrieving address. Please confirm on your Ledger
Address: erd1r27kar...yq3a8tj0
Sender shard: 0
Balance: 0 ERD
Nonce: 0
Enter destination address:
```

I assume the [truncated] address `erd1r27kar...yq3a8tj0` was my Elrond wallet address for receiving ERD but when I try to transfer ERD into my wallet using that address I get an error saying it isn't a valid Elrond address.  Using the official API I get:

https://api.elrond.com/address/:erd1r27kar...yq3a8tj0
`{"data":null,"error":"checksum failed. Expected dls050, got 3a8tj0.","code":"internal_issue"}`

Is there another place I should be looking for the receiving address on my Nano Ledger S?

**Comment by mihaib79** [comment]
Hello.
This implementation is for native eGLD tokens. I presume you tried to send ERC20 or BEP2 ERD in the address generated by the NanoS, and that's why it said "not a valid Elrond address".
To use the official API, please omit the ":" from the address route.
Looking forward to your feedback after you update to the latest version (Ledger Live 2.9 or 2.10, NanoS firmware 1.6.1, Elrond app version 1.0.4 - Development mode)
Best regards
