### ISSUE TITLE
multiple wallets after update

### ISSUE THREAD

**Issue by tntmario** [ElrondNetwork/ledger-elrond#27]
After updating to 1.0.8 i have multiple wallets when accessing the elrond wallet with ledger.
Before the update, connecting the ledger to the computer will only forward me to my main wallet. After the update i get a high number of wallets to choose from (please see attached picture). Only the first wallet contains the amount of money i had before.
If i click next, a new page of empty wallets are displayed.

The load time for connection is significantly increased as ledger has to load all these empty wallets before it confirms what wallet needs to be accessed.
![image](https://user-images.githubusercontent.com/29608719/106253397-1b370c00-6220-11eb-9216-db9f5964a3ee.png)

**Comment by AdoAdoAdo** [comment]
This is part of the implemented feature for generating hierarchical deterministic wallets through key derivation. 
Previously you had access only to the first index wallet (which is the one with funds). You can recover all these wallets from the same seed phrase.

The other wallets are empty since no one transferred funds there, but you can use any of them and since you have access to their private key and can sign transactions from any of those wallets.

Indeed the load time has increased, but this was expected with this update.

**Comment by tntmario** [comment]
Hello Ado,

Thank you very much for the explanation. This makes sense :D.

I will close the issue.
